version: '2'

services:
  litecoind:
    build: ./data-sources/litecoind
    volumes:
      - ./data-sources/litecoind/litecoin.conf:/home/litecoin/.litecoin/litecoin.conf
    command: litecoind  --datadir=/home/litecoin/.litecoin --printtoconsole -rpcallowip=0.0.0.0/0
    ports:
      - "19332:19332"
  bitcoind:
    build: ./data-sources/bitcoind
    volumes:
      - ./data-sources/bitcoind/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
    command: bitcoind  --datadir=/home/bitcoin/.bitcoin --printtoconsole -rpcallowip=0.0.0.0/0
    ports:
      - "18332:18332"
