version: '2'

services:
  litecoind:
    build: ./data-sources/litecoind
    volumes:
      - ./data-sources/litecoind/litecoin.conf:/home/litecoin/.litecoin/litecoin.conf
    command: litecoind  --datadir=/home/litecoin/.litecoin --printtoconsole -rpcallowip=0.0.0.0/0
    ports:
      - "19443:19443"
      - "29332:29332"
      - "29333:29333"
  bitcoind:
    build: ./data-sources/bitcoind
    volumes:
      - ./data-sources/bitcoind/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
    command: bitcoind  --datadir=/home/bitcoin/.bitcoin --printtoconsole -rpcallowip=0.0.0.0/0
    ports:
      - "18443:18443"
      - "28332:28332"
      - "28333:28333"
  mongodb:
    build: ./data-sources/mongodb
    volumes:
      - ./data-sources/mongodb/mongod.conf:/etc/mongod.conf
    command: mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
